services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: https://emanuelbarboza.com

    container_name: emanuelbarboza-web
    restart: unless-stopped

    environment:
      NODE_ENV: production
      PORT: "3000"

    ports:
      - "3002:3000"